#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="IPETGODATABASE")]
public partial class iPetGoDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 擴充性方法定義
  partial void OnCreated();
  partial void InsertAdvancedMember(AdvancedMember instance);
  partial void UpdateAdvancedMember(AdvancedMember instance);
  partial void DeleteAdvancedMember(AdvancedMember instance);
  partial void InsertMember(Member instance);
  partial void UpdateMember(Member instance);
  partial void DeleteMember(Member instance);
  partial void InserttSitterDetail(tSitterDetail instance);
  partial void UpdatetSitterDetail(tSitterDetail instance);
  partial void DeletetSitterDetail(tSitterDetail instance);
  #endregion
	
	public iPetGoDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["iPetGoConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public iPetGoDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public iPetGoDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public iPetGoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public iPetGoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<AdvancedMember> AdvancedMember
	{
		get
		{
			return this.GetTable<AdvancedMember>();
		}
	}
	
	public System.Data.Linq.Table<Member> Member
	{
		get
		{
			return this.GetTable<Member>();
		}
	}
	
	public System.Data.Linq.Table<tSitterDetail> tSitterDetail
	{
		get
		{
			return this.GetTable<tSitterDetail>();
		}
	}
	
	public System.Data.Linq.Table<tSitterServiceStatus> tSitterServiceStatus
	{
		get
		{
			return this.GetTable<tSitterServiceStatus>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdvancedMember")]
public partial class AdvancedMember : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _MemberId;
	
	private string _fServiceName;
	
	private string _fIntro;
	
	private string _fMainType;
	
	private System.Nullable<int> _fSeniority;
	
	private string _fNote;
	
	private string _fPhone;
	
	private string _fTeltimeWeek;
	
	private string _fTeltime;
	
	private string _fSurround;
	
	private string _fCountry;
	
	private string _fArea;
	
	private string _fAddress;
	
	private System.Nullable<int> _fStayPay;
	
	private System.Nullable<bool> _fLicenseHave;
	
	private string _fImage;
	
	private EntitySet<tSitterDetail> _tSitterDetail;
	
	private EntityRef<Member> _Member;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMemberIdChanging(int value);
    partial void OnMemberIdChanged();
    partial void OnfServiceNameChanging(string value);
    partial void OnfServiceNameChanged();
    partial void OnfIntroChanging(string value);
    partial void OnfIntroChanged();
    partial void OnfMainTypeChanging(string value);
    partial void OnfMainTypeChanged();
    partial void OnfSeniorityChanging(System.Nullable<int> value);
    partial void OnfSeniorityChanged();
    partial void OnfNoteChanging(string value);
    partial void OnfNoteChanged();
    partial void OnfPhoneChanging(string value);
    partial void OnfPhoneChanged();
    partial void OnfTeltimeWeekChanging(string value);
    partial void OnfTeltimeWeekChanged();
    partial void OnfTeltimeChanging(string value);
    partial void OnfTeltimeChanged();
    partial void OnfSurroundChanging(string value);
    partial void OnfSurroundChanged();
    partial void OnfCountryChanging(string value);
    partial void OnfCountryChanged();
    partial void OnfAreaChanging(string value);
    partial void OnfAreaChanged();
    partial void OnfAddressChanging(string value);
    partial void OnfAddressChanged();
    partial void OnfStayPayChanging(System.Nullable<int> value);
    partial void OnfStayPayChanged();
    partial void OnfLicenseHaveChanging(System.Nullable<bool> value);
    partial void OnfLicenseHaveChanged();
    partial void OnfImageChanging(string value);
    partial void OnfImageChanged();
    #endregion
	
	public AdvancedMember()
	{
		this._tSitterDetail = new EntitySet<tSitterDetail>(new Action<tSitterDetail>(this.attach_tSitterDetail), new Action<tSitterDetail>(this.detach_tSitterDetail));
		this._Member = default(EntityRef<Member>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberId", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int MemberId
	{
		get
		{
			return this._MemberId;
		}
		set
		{
			if ((this._MemberId != value))
			{
				if (this._Member.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMemberIdChanging(value);
				this.SendPropertyChanging();
				this._MemberId = value;
				this.SendPropertyChanged("MemberId");
				this.OnMemberIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fServiceName", DbType="NVarChar(MAX)")]
	public string fServiceName
	{
		get
		{
			return this._fServiceName;
		}
		set
		{
			if ((this._fServiceName != value))
			{
				this.OnfServiceNameChanging(value);
				this.SendPropertyChanging();
				this._fServiceName = value;
				this.SendPropertyChanged("fServiceName");
				this.OnfServiceNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fIntro", DbType="NVarChar(MAX)")]
	public string fIntro
	{
		get
		{
			return this._fIntro;
		}
		set
		{
			if ((this._fIntro != value))
			{
				this.OnfIntroChanging(value);
				this.SendPropertyChanging();
				this._fIntro = value;
				this.SendPropertyChanged("fIntro");
				this.OnfIntroChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fMainType", DbType="NVarChar(MAX)")]
	public string fMainType
	{
		get
		{
			return this._fMainType;
		}
		set
		{
			if ((this._fMainType != value))
			{
				this.OnfMainTypeChanging(value);
				this.SendPropertyChanging();
				this._fMainType = value;
				this.SendPropertyChanged("fMainType");
				this.OnfMainTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fSeniority", DbType="Int")]
	public System.Nullable<int> fSeniority
	{
		get
		{
			return this._fSeniority;
		}
		set
		{
			if ((this._fSeniority != value))
			{
				this.OnfSeniorityChanging(value);
				this.SendPropertyChanging();
				this._fSeniority = value;
				this.SendPropertyChanged("fSeniority");
				this.OnfSeniorityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fNote", DbType="NVarChar(MAX)")]
	public string fNote
	{
		get
		{
			return this._fNote;
		}
		set
		{
			if ((this._fNote != value))
			{
				this.OnfNoteChanging(value);
				this.SendPropertyChanging();
				this._fNote = value;
				this.SendPropertyChanged("fNote");
				this.OnfNoteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fPhone", DbType="NVarChar(MAX)")]
	public string fPhone
	{
		get
		{
			return this._fPhone;
		}
		set
		{
			if ((this._fPhone != value))
			{
				this.OnfPhoneChanging(value);
				this.SendPropertyChanging();
				this._fPhone = value;
				this.SendPropertyChanged("fPhone");
				this.OnfPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fTeltimeWeek", DbType="NVarChar(MAX)")]
	public string fTeltimeWeek
	{
		get
		{
			return this._fTeltimeWeek;
		}
		set
		{
			if ((this._fTeltimeWeek != value))
			{
				this.OnfTeltimeWeekChanging(value);
				this.SendPropertyChanging();
				this._fTeltimeWeek = value;
				this.SendPropertyChanged("fTeltimeWeek");
				this.OnfTeltimeWeekChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fTeltime", DbType="NVarChar(MAX)")]
	public string fTeltime
	{
		get
		{
			return this._fTeltime;
		}
		set
		{
			if ((this._fTeltime != value))
			{
				this.OnfTeltimeChanging(value);
				this.SendPropertyChanging();
				this._fTeltime = value;
				this.SendPropertyChanged("fTeltime");
				this.OnfTeltimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fSurround", DbType="NVarChar(MAX)")]
	public string fSurround
	{
		get
		{
			return this._fSurround;
		}
		set
		{
			if ((this._fSurround != value))
			{
				this.OnfSurroundChanging(value);
				this.SendPropertyChanging();
				this._fSurround = value;
				this.SendPropertyChanged("fSurround");
				this.OnfSurroundChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fCountry", DbType="NVarChar(MAX)")]
	public string fCountry
	{
		get
		{
			return this._fCountry;
		}
		set
		{
			if ((this._fCountry != value))
			{
				this.OnfCountryChanging(value);
				this.SendPropertyChanging();
				this._fCountry = value;
				this.SendPropertyChanged("fCountry");
				this.OnfCountryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fArea", DbType="NVarChar(MAX)")]
	public string fArea
	{
		get
		{
			return this._fArea;
		}
		set
		{
			if ((this._fArea != value))
			{
				this.OnfAreaChanging(value);
				this.SendPropertyChanging();
				this._fArea = value;
				this.SendPropertyChanged("fArea");
				this.OnfAreaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAddress", DbType="NVarChar(MAX)")]
	public string fAddress
	{
		get
		{
			return this._fAddress;
		}
		set
		{
			if ((this._fAddress != value))
			{
				this.OnfAddressChanging(value);
				this.SendPropertyChanging();
				this._fAddress = value;
				this.SendPropertyChanged("fAddress");
				this.OnfAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fStayPay", DbType="Int")]
	public System.Nullable<int> fStayPay
	{
		get
		{
			return this._fStayPay;
		}
		set
		{
			if ((this._fStayPay != value))
			{
				this.OnfStayPayChanging(value);
				this.SendPropertyChanging();
				this._fStayPay = value;
				this.SendPropertyChanged("fStayPay");
				this.OnfStayPayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fLicenseHave", DbType="Bit")]
	public System.Nullable<bool> fLicenseHave
	{
		get
		{
			return this._fLicenseHave;
		}
		set
		{
			if ((this._fLicenseHave != value))
			{
				this.OnfLicenseHaveChanging(value);
				this.SendPropertyChanging();
				this._fLicenseHave = value;
				this.SendPropertyChanged("fLicenseHave");
				this.OnfLicenseHaveChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fImage", DbType="NVarChar(300)")]
	public string fImage
	{
		get
		{
			return this._fImage;
		}
		set
		{
			if ((this._fImage != value))
			{
				this.OnfImageChanging(value);
				this.SendPropertyChanging();
				this._fImage = value;
				this.SendPropertyChanged("fImage");
				this.OnfImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AdvancedMember_tSitterDetail", Storage="_tSitterDetail", ThisKey="MemberId", OtherKey="fSitterid")]
	public EntitySet<tSitterDetail> tSitterDetail
	{
		get
		{
			return this._tSitterDetail;
		}
		set
		{
			this._tSitterDetail.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Member_AdvancedMember", Storage="_Member", ThisKey="MemberId", OtherKey="MemberId", IsForeignKey=true)]
	public Member Member
	{
		get
		{
			return this._Member.Entity;
		}
		set
		{
			Member previousValue = this._Member.Entity;
			if (((previousValue != value) 
						|| (this._Member.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Member.Entity = null;
					previousValue.AdvancedMember = null;
				}
				this._Member.Entity = value;
				if ((value != null))
				{
					value.AdvancedMember = this;
					this._MemberId = value.MemberId;
				}
				else
				{
					this._MemberId = default(int);
				}
				this.SendPropertyChanged("Member");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tSitterDetail(tSitterDetail entity)
	{
		this.SendPropertyChanging();
		entity.AdvancedMember = this;
	}
	
	private void detach_tSitterDetail(tSitterDetail entity)
	{
		this.SendPropertyChanging();
		entity.AdvancedMember = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Member")]
public partial class Member : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _MemberId;
	
	private string _MemberAccount;
	
	private string _MemberPassword;
	
	private string _MemberName;
	
	private string _sex;
	
	private string _MemberEmail;
	
	private System.Nullable<int> _fRight;
	
	private string _MemberImage;
	
	private System.Nullable<bool> _fCheck;
	
	private EntityRef<AdvancedMember> _AdvancedMember;
	
	private EntitySet<tSitterDetail> _tSitterDetail;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMemberIdChanging(int value);
    partial void OnMemberIdChanged();
    partial void OnMemberAccountChanging(string value);
    partial void OnMemberAccountChanged();
    partial void OnMemberPasswordChanging(string value);
    partial void OnMemberPasswordChanged();
    partial void OnMemberNameChanging(string value);
    partial void OnMemberNameChanged();
    partial void OnsexChanging(string value);
    partial void OnsexChanged();
    partial void OnMemberEmailChanging(string value);
    partial void OnMemberEmailChanged();
    partial void OnfRightChanging(System.Nullable<int> value);
    partial void OnfRightChanged();
    partial void OnMemberImageChanging(string value);
    partial void OnMemberImageChanged();
    partial void OnfCheckChanging(System.Nullable<bool> value);
    partial void OnfCheckChanged();
    #endregion
	
	public Member()
	{
		this._AdvancedMember = default(EntityRef<AdvancedMember>);
		this._tSitterDetail = new EntitySet<tSitterDetail>(new Action<tSitterDetail>(this.attach_tSitterDetail), new Action<tSitterDetail>(this.detach_tSitterDetail));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int MemberId
	{
		get
		{
			return this._MemberId;
		}
		set
		{
			if ((this._MemberId != value))
			{
				this.OnMemberIdChanging(value);
				this.SendPropertyChanging();
				this._MemberId = value;
				this.SendPropertyChanged("MemberId");
				this.OnMemberIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberAccount", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string MemberAccount
	{
		get
		{
			return this._MemberAccount;
		}
		set
		{
			if ((this._MemberAccount != value))
			{
				this.OnMemberAccountChanging(value);
				this.SendPropertyChanging();
				this._MemberAccount = value;
				this.SendPropertyChanged("MemberAccount");
				this.OnMemberAccountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberPassword", DbType="NVarChar(50)")]
	public string MemberPassword
	{
		get
		{
			return this._MemberPassword;
		}
		set
		{
			if ((this._MemberPassword != value))
			{
				this.OnMemberPasswordChanging(value);
				this.SendPropertyChanging();
				this._MemberPassword = value;
				this.SendPropertyChanged("MemberPassword");
				this.OnMemberPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberName", DbType="NVarChar(MAX)")]
	public string MemberName
	{
		get
		{
			return this._MemberName;
		}
		set
		{
			if ((this._MemberName != value))
			{
				this.OnMemberNameChanging(value);
				this.SendPropertyChanging();
				this._MemberName = value;
				this.SendPropertyChanged("MemberName");
				this.OnMemberNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="NVarChar(MAX)")]
	public string sex
	{
		get
		{
			return this._sex;
		}
		set
		{
			if ((this._sex != value))
			{
				this.OnsexChanging(value);
				this.SendPropertyChanging();
				this._sex = value;
				this.SendPropertyChanged("sex");
				this.OnsexChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberEmail", DbType="NVarChar(MAX)")]
	public string MemberEmail
	{
		get
		{
			return this._MemberEmail;
		}
		set
		{
			if ((this._MemberEmail != value))
			{
				this.OnMemberEmailChanging(value);
				this.SendPropertyChanging();
				this._MemberEmail = value;
				this.SendPropertyChanged("MemberEmail");
				this.OnMemberEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fRight", DbType="Int")]
	public System.Nullable<int> fRight
	{
		get
		{
			return this._fRight;
		}
		set
		{
			if ((this._fRight != value))
			{
				this.OnfRightChanging(value);
				this.SendPropertyChanging();
				this._fRight = value;
				this.SendPropertyChanged("fRight");
				this.OnfRightChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberImage", DbType="NVarChar(250)")]
	public string MemberImage
	{
		get
		{
			return this._MemberImage;
		}
		set
		{
			if ((this._MemberImage != value))
			{
				this.OnMemberImageChanging(value);
				this.SendPropertyChanging();
				this._MemberImage = value;
				this.SendPropertyChanged("MemberImage");
				this.OnMemberImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fCheck", DbType="Bit")]
	public System.Nullable<bool> fCheck
	{
		get
		{
			return this._fCheck;
		}
		set
		{
			if ((this._fCheck != value))
			{
				this.OnfCheckChanging(value);
				this.SendPropertyChanging();
				this._fCheck = value;
				this.SendPropertyChanged("fCheck");
				this.OnfCheckChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Member_AdvancedMember", Storage="_AdvancedMember", ThisKey="MemberId", OtherKey="MemberId", IsUnique=true, IsForeignKey=false)]
	public AdvancedMember AdvancedMember
	{
		get
		{
			return this._AdvancedMember.Entity;
		}
		set
		{
			AdvancedMember previousValue = this._AdvancedMember.Entity;
			if (((previousValue != value) 
						|| (this._AdvancedMember.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._AdvancedMember.Entity = null;
					previousValue.Member = null;
				}
				this._AdvancedMember.Entity = value;
				if ((value != null))
				{
					value.Member = this;
				}
				this.SendPropertyChanged("AdvancedMember");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Member_tSitterDetail", Storage="_tSitterDetail", ThisKey="MemberId", OtherKey="MemberId")]
	public EntitySet<tSitterDetail> tSitterDetail
	{
		get
		{
			return this._tSitterDetail;
		}
		set
		{
			this._tSitterDetail.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tSitterDetail(tSitterDetail entity)
	{
		this.SendPropertyChanging();
		entity.Member = this;
	}
	
	private void detach_tSitterDetail(tSitterDetail entity)
	{
		this.SendPropertyChanging();
		entity.Member = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tSitterDetail")]
public partial class tSitterDetail : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _fId;
	
	private int _fSitterid;
	
	private System.Nullable<int> _MemberId;
	
	private string _fPetId;
	
	private string _fService;
	
	private System.Nullable<System.DateTime> _fStartDate;
	
	private System.Nullable<System.DateTime> _fEndDate;
	
	private string _fMessage;
	
	private System.Nullable<int> _fEvaluation;
	
	private string _fComment;
	
	private System.Nullable<int> _fStatus;
	
	private EntityRef<AdvancedMember> _AdvancedMember;
	
	private EntityRef<Member> _Member;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfIdChanging(int value);
    partial void OnfIdChanged();
    partial void OnfSitteridChanging(int value);
    partial void OnfSitteridChanged();
    partial void OnMemberIdChanging(System.Nullable<int> value);
    partial void OnMemberIdChanged();
    partial void OnfPetIdChanging(string value);
    partial void OnfPetIdChanged();
    partial void OnfServiceChanging(string value);
    partial void OnfServiceChanged();
    partial void OnfStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnfStartDateChanged();
    partial void OnfEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnfEndDateChanged();
    partial void OnfMessageChanging(string value);
    partial void OnfMessageChanged();
    partial void OnfEvaluationChanging(System.Nullable<int> value);
    partial void OnfEvaluationChanged();
    partial void OnfCommentChanging(string value);
    partial void OnfCommentChanged();
    partial void OnfStatusChanging(System.Nullable<int> value);
    partial void OnfStatusChanged();
    #endregion
	
	public tSitterDetail()
	{
		this._AdvancedMember = default(EntityRef<AdvancedMember>);
		this._Member = default(EntityRef<Member>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int fId
	{
		get
		{
			return this._fId;
		}
		set
		{
			if ((this._fId != value))
			{
				this.OnfIdChanging(value);
				this.SendPropertyChanging();
				this._fId = value;
				this.SendPropertyChanged("fId");
				this.OnfIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fSitterid", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int fSitterid
	{
		get
		{
			return this._fSitterid;
		}
		set
		{
			if ((this._fSitterid != value))
			{
				if (this._AdvancedMember.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnfSitteridChanging(value);
				this.SendPropertyChanging();
				this._fSitterid = value;
				this.SendPropertyChanged("fSitterid");
				this.OnfSitteridChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberId", DbType="Int")]
	public System.Nullable<int> MemberId
	{
		get
		{
			return this._MemberId;
		}
		set
		{
			if ((this._MemberId != value))
			{
				if (this._Member.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMemberIdChanging(value);
				this.SendPropertyChanging();
				this._MemberId = value;
				this.SendPropertyChanged("MemberId");
				this.OnMemberIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fPetId", DbType="NVarChar(50)")]
	public string fPetId
	{
		get
		{
			return this._fPetId;
		}
		set
		{
			if ((this._fPetId != value))
			{
				this.OnfPetIdChanging(value);
				this.SendPropertyChanging();
				this._fPetId = value;
				this.SendPropertyChanged("fPetId");
				this.OnfPetIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fService", DbType="NVarChar(50)")]
	public string fService
	{
		get
		{
			return this._fService;
		}
		set
		{
			if ((this._fService != value))
			{
				this.OnfServiceChanging(value);
				this.SendPropertyChanging();
				this._fService = value;
				this.SendPropertyChanged("fService");
				this.OnfServiceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fStartDate", DbType="Date")]
	public System.Nullable<System.DateTime> fStartDate
	{
		get
		{
			return this._fStartDate;
		}
		set
		{
			if ((this._fStartDate != value))
			{
				this.OnfStartDateChanging(value);
				this.SendPropertyChanging();
				this._fStartDate = value;
				this.SendPropertyChanged("fStartDate");
				this.OnfStartDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fEndDate", DbType="Date")]
	public System.Nullable<System.DateTime> fEndDate
	{
		get
		{
			return this._fEndDate;
		}
		set
		{
			if ((this._fEndDate != value))
			{
				this.OnfEndDateChanging(value);
				this.SendPropertyChanging();
				this._fEndDate = value;
				this.SendPropertyChanged("fEndDate");
				this.OnfEndDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fMessage", DbType="NVarChar(200)")]
	public string fMessage
	{
		get
		{
			return this._fMessage;
		}
		set
		{
			if ((this._fMessage != value))
			{
				this.OnfMessageChanging(value);
				this.SendPropertyChanging();
				this._fMessage = value;
				this.SendPropertyChanged("fMessage");
				this.OnfMessageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fEvaluation", DbType="Int")]
	public System.Nullable<int> fEvaluation
	{
		get
		{
			return this._fEvaluation;
		}
		set
		{
			if ((this._fEvaluation != value))
			{
				this.OnfEvaluationChanging(value);
				this.SendPropertyChanging();
				this._fEvaluation = value;
				this.SendPropertyChanged("fEvaluation");
				this.OnfEvaluationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fComment", DbType="NVarChar(100)")]
	public string fComment
	{
		get
		{
			return this._fComment;
		}
		set
		{
			if ((this._fComment != value))
			{
				this.OnfCommentChanging(value);
				this.SendPropertyChanging();
				this._fComment = value;
				this.SendPropertyChanged("fComment");
				this.OnfCommentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fStatus", DbType="Int")]
	public System.Nullable<int> fStatus
	{
		get
		{
			return this._fStatus;
		}
		set
		{
			if ((this._fStatus != value))
			{
				this.OnfStatusChanging(value);
				this.SendPropertyChanging();
				this._fStatus = value;
				this.SendPropertyChanged("fStatus");
				this.OnfStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AdvancedMember_tSitterDetail", Storage="_AdvancedMember", ThisKey="fSitterid", OtherKey="MemberId", IsForeignKey=true)]
	public AdvancedMember AdvancedMember
	{
		get
		{
			return this._AdvancedMember.Entity;
		}
		set
		{
			AdvancedMember previousValue = this._AdvancedMember.Entity;
			if (((previousValue != value) 
						|| (this._AdvancedMember.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._AdvancedMember.Entity = null;
					previousValue.tSitterDetail.Remove(this);
				}
				this._AdvancedMember.Entity = value;
				if ((value != null))
				{
					value.tSitterDetail.Add(this);
					this._fSitterid = value.MemberId;
				}
				else
				{
					this._fSitterid = default(int);
				}
				this.SendPropertyChanged("AdvancedMember");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Member_tSitterDetail", Storage="_Member", ThisKey="MemberId", OtherKey="MemberId", IsForeignKey=true)]
	public Member Member
	{
		get
		{
			return this._Member.Entity;
		}
		set
		{
			Member previousValue = this._Member.Entity;
			if (((previousValue != value) 
						|| (this._Member.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Member.Entity = null;
					previousValue.tSitterDetail.Remove(this);
				}
				this._Member.Entity = value;
				if ((value != null))
				{
					value.tSitterDetail.Add(this);
					this._MemberId = value.MemberId;
				}
				else
				{
					this._MemberId = default(Nullable<int>);
				}
				this.SendPropertyChanged("Member");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tSitterServiceStatus")]
public partial class tSitterServiceStatus
{
	
	private int _fStatus;
	
	private string _fdescription;
	
	public tSitterServiceStatus()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fStatus", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int fStatus
	{
		get
		{
			return this._fStatus;
		}
		set
		{
			if ((this._fStatus != value))
			{
				this._fStatus = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fdescription", DbType="NVarChar(50)")]
	public string fdescription
	{
		get
		{
			return this._fdescription;
		}
		set
		{
			if ((this._fdescription != value))
			{
				this._fdescription = value;
			}
		}
	}
}
#pragma warning restore 1591
